services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cv-curriculum-vitae-backend
    env_file: .env
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - '3000:3000'
    volumes:
      - .:/home/cv/app
    restart: unless-stopped
