services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - NODE_ENV=production
      - PORT=3001
    ports:
      - "3001:3001" # Ánh xạ cổng 3000 của container đến cổng 3000 của máy chủ
    restart: unless-stopped
